server:
  port: 8088
spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/message
    encoding: UTF-8
    default-locale: en

api:
  prefix: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health
    health:
      show-details: always

jwt:
  expiration: 604800  #  30 day = 30 * 24 * 60 * 60
  secretKey: ZYyCCIBHgKvbfuB1uKJowZyVGhpFXhuiqaDMZNwHlns=

